substitutions:
  device_name: fitpro
  friendly_name: FitPro smart band

esphome:
  name: ${device_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

external_components:
  - source: github://andyboeh/esphome-fitpro
    components: fitpro


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} HS"
    password: !secret Fallback_Hotspot
    ap_timeout: 1min

esp32_ble_tracker:

ble_client:
  - mac_address: AA:BB:CC:DD:EE:FF
    id: my_fitpro_ble

fitpro:
  - ble_client_id: my_fitpro_ble
    id: my_fitpro

# Example configuration entry
sensor:
  - platform: fitpro
    id: my_fitpro
    battery_level: 
      name: Battery Level
  # Uptime sensor
  - platform: uptime
    name: ${friendly_name} Uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s
    
# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
  - platform: fitpro
    id: my_fitpro
    status:
      name: State

